### ISSUE TITLE
"updated by" -- without asking

### ISSUE THREAD

**Issue by sturobson** [TheJaredWilcurt/SassNotSASS#1]

**Comment by sturobson** [comment]
*coughs*

You don't need this now - the site lives.

**Comment by sturobson** [comment]
ok, no need to portray "the dick" in OSS ... have a great time.

**Comment by TheJaredWilcurt** [comment]
I sent you a message inquiring why the site was down. I asked what the deal was with it. Did you not care anymore? Did you not want to spend money on hosting or the domain? I didn't know what your problem was.

I went through and remade the whole thing, updated it to be responsive, support more devices, have a higher quality image, be more optimized, and set it up on free hosting.

[You're the dick, fuck you](https://twitter.com/StuRobson/status/784823548762357765).

Leave me alone.

**Comment by sturobson** [comment]
Ok, wow. I didn't call you a dick but thanks for calling me one. Anyway - it's been here - http://sassnotsass.com - since around the 16th of October.

All the best in whatever you do.
